version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: ./mvnw spring-boot:run

  frontend:
    build:
      context: .
      dockerfile: ./front/Dockerfile
      target: development
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5173

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CRUD
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
