up:
	docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d

down:
	docker compose -f docker-compose.yml -f docker-compose.dev.yml down

stop:
	docker compose -f docker-compose.yml -f docker-compose.dev.yml stop

start:
	docker compose -f docker-compose.yml -f docker-compose.dev.yml start

logs:
	docker compose -f docker-compose.yml -f docker-compose.dev.yml logs -f

ps:
	docker compose -f docker-compose.yml -f docker-compose.dev.yml ps